// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _06_Fiap.Web.AspNet.Contexts;

namespace _06_Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(CartaoContext))]
    [Migration("20190920012045_CartaoMigration")]
    partial class CartaoMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.Banco", b =>
                {
                    b.Property<int>("BancoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Agencia");

                    b.Property<string>("Nome");

                    b.Property<int>("Numero");

                    b.HasKey("BancoId");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.Cartao", b =>
                {
                    b.Property<int>("CartaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BancoId");

                    b.Property<int>("Bandeira");

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("DataValidade");

                    b.Property<bool>("Internacional");

                    b.Property<decimal>("Limite");

                    b.Property<string>("Nome");

                    b.HasKey("CartaoId");

                    b.HasIndex("BancoId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Nome");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.FundoInvestimento", b =>
                {
                    b.Property<int>("FundoInvestimentoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome");

                    b.Property<decimal>("Rendimento");

                    b.Property<decimal>("ValorMinimo");

                    b.HasKey("FundoInvestimentoId");

                    b.ToTable("FundoInvestimentos");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.FundoInvestimentoBanco", b =>
                {
                    b.Property<int>("BancoId");

                    b.Property<int>("FundoInvestimentoId");

                    b.HasKey("BancoId", "FundoInvestimentoId");

                    b.HasIndex("FundoInvestimentoId");

                    b.ToTable("FundoInvestimentoBanco");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.Cartao", b =>
                {
                    b.HasOne("_06_Fiap.Web.AspNet.Models.Banco", "Banco")
                        .WithMany("Cartoes")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_06_Fiap.Web.AspNet.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("_06_Fiap.Web.AspNet.Models.FundoInvestimentoBanco", b =>
                {
                    b.HasOne("_06_Fiap.Web.AspNet.Models.Banco", "Banco")
                        .WithMany("FundoInvestimentoBancos")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("_06_Fiap.Web.AspNet.Models.FundoInvestimento", "FundoInvestimento")
                        .WithMany("FundoInvestimentoBancos")
                        .HasForeignKey("FundoInvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
