CREATE TABLE TB_STAGE_CLI
   (	SK_CLI NUMBER, 
	NR_CPF VARCHAR2(20 BYTE), 
	NM_CLIENTE VARCHAR2(60 BYTE), 
	NM_SEXO VARCHAR2(15 BYTE), 
	NM_ESTADO_CIVIL VARCHAR2(30 BYTE), 
	NM_ESCOLARIDADE VARCHAR2(30 BYTE), 
	NM_REGIAO VARCHAR2(15 BYTE), 
	SG_ESTADO VARCHAR2(2 BYTE), 
	NM_ESTADO VARCHAR2(30 BYTE), 
	NM_CIDADE VARCHAR2(40 BYTE), 
	NM_BAIRRO VARCHAR2(40 BYTE)
   ) SEGMENT CREATION DEFERRED 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
TABLESPACE TBSPC_ALUNOS ;