DROP TABLE dim_prod_serv CASCADE CONSTRAINTS;

DROP TABLE dim_promocao CASCADE CONSTRAINTS;

DROP TABLE dim_tempo CASCADE CONSTRAINTS;

DROP TABLE dim_unidade CASCADE CONSTRAINTS;

DROP TABLE fto_venda CASCADE CONSTRAINTS;