-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-09-03 20:50:36 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE dim_prod_serv (
    sk_prod_serv   NUMBER NOT NULL,
    nm_prod_serv   VARCHAR2(50)
);

ALTER TABLE dim_prod_serv ADD CONSTRAINT dim_prod_serv_pk PRIMARY KEY ( sk_prod_serv );

CREATE TABLE dim_promocao (
    sk_desconto     NUMBER NOT NULL,
    nm_promocao     VARCHAR2(50),
    perc_desconto   FLOAT,
    dt_inicio       DATE,
    dt_fim          DATE
);

ALTER TABLE dim_promocao ADD CONSTRAINT dim_promocao_pk PRIMARY KEY ( sk_desconto );

CREATE TABLE dim_tempo (
    sk_tempo        NUMBER NOT NULL,
    dt_inicio       DATE,
    dt_fim          DATE,
    dia             NUMBER,
    mes             NUMBER,
    ano             NUMBER,
    dia_da_semana   VARCHAR2(20)
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE dim_unidade (
    sk_unidade   NUMBER NOT NULL,
    nm_unidade   VARCHAR2(100),
    estado       VARCHAR2(2),
    cidade       VARCHAR2(20),
    bairro       VARCHAR2(20),
    logradouro   VARCHAR2(100),
    cnpj         VARCHAR2(19)
);

ALTER TABLE dim_unidade ADD CONSTRAINT dim_unidade_pk PRIMARY KEY ( sk_unidade );

CREATE TABLE fto_venda (
    sk_venda            NUMBER NOT NULL,
    sk_tempo            NUMBER NOT NULL,
    sk_prod_serv        NUMBER NOT NULL,
    sk_unidade          NUMBER NOT NULL,
    sk_desconto         NUMBER NOT NULL,
    total_vendas        NUMBER,
    produtos_vendidos   NUMBER,
    valor_icms          FLOAT,
    lucro_liquido       FLOAT
);

ALTER TABLE fto_venda ADD CONSTRAINT fto_venda_pk PRIMARY KEY ( sk_venda );

ALTER TABLE fto_venda
    ADD CONSTRAINT prod_serv_fk FOREIGN KEY ( sk_prod_serv )
        REFERENCES dim_prod_serv ( sk_prod_serv );

ALTER TABLE fto_venda
    ADD CONSTRAINT promocao_fk FOREIGN KEY ( sk_desconto )
        REFERENCES dim_promocao ( sk_desconto );

ALTER TABLE fto_venda
    ADD CONSTRAINT tempo_fk FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );

ALTER TABLE fto_venda
    ADD CONSTRAINT unidade_fk FOREIGN KEY ( sk_unidade )
        REFERENCES dim_unidade ( sk_unidade );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
