-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-09-24 20:01:54 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE dim_penalidade (
    sk_penalidade        NUMBER NOT NULL,
    ds_tipo              VARCHAR2(10),
    ds_veloc_permitida   NUMBER
);

ALTER TABLE dim_penalidade ADD CONSTRAINT dim_penalidade_pk PRIMARY KEY ( sk_penalidade );

CREATE TABLE dim_regiao (
    sk_regiao      NUMBER NOT NULL,
    ds_quadrante   NUMBER,
    ds_regiao      VARCHAR2(100)
);

ALTER TABLE dim_regiao ADD CONSTRAINT dim_regiao_pk PRIMARY KEY ( sk_regiao );

CREATE TABLE dim_tempo (
    sk_tempo     NUMBER NOT NULL,
    ds_hora      DATE,
    ds_dia       NUMBER,
    ds_mes       NUMBER,
    ds_feriado   NUMBER
);

ALTER TABLE dim_tempo ADD CONSTRAINT dim_tempo_pk PRIMARY KEY ( sk_tempo );

CREATE TABLE dim_veiculo (
    sk_veiculo       NUMBER NOT NULL,
    ds_placa         VARCHAR2(10),
    ds_tipo          VARCHAR2(50),
    ds_veloc_media   NUMBER
);

ALTER TABLE dim_veiculo ADD CONSTRAINT dim_veiculo_pk PRIMARY KEY ( sk_veiculo );

CREATE TABLE fto_ocorrencias (
    sk_ocorrencia         NUMBER NOT NULL,
    sk_penalidade         NUMBER NOT NULL,
    sk_tempo              NUMBER NOT NULL,
    sk_regiao             NUMBER NOT NULL,
    sk_veiculo            NUMBER NOT NULL,
    vl_penalidade         NUMBER,
    vl_total_penalidade   NUMBER,
    vl_volume_veiculos    NUMBER,
    ds_perc_penalidades   NUMBER
);

ALTER TABLE fto_ocorrencias
    ADD CONSTRAINT fto_ocorrencias_pk PRIMARY KEY ( sk_ocorrencia,
                                                    sk_penalidade,
                                                    sk_tempo,
                                                    sk_regiao,
                                                    sk_veiculo );

ALTER TABLE fto_ocorrencias
    ADD CONSTRAINT fk_penalidade_fto FOREIGN KEY ( sk_penalidade )
        REFERENCES dim_penalidade ( sk_penalidade );

ALTER TABLE fto_ocorrencias
    ADD CONSTRAINT fk_regiao_fto FOREIGN KEY ( sk_regiao )
        REFERENCES dim_regiao ( sk_regiao );

ALTER TABLE fto_ocorrencias
    ADD CONSTRAINT fk_tempo_fto FOREIGN KEY ( sk_tempo )
        REFERENCES dim_tempo ( sk_tempo );

ALTER TABLE fto_ocorrencias
    ADD CONSTRAINT fk_veiculo_fto FOREIGN KEY ( sk_veiculo )
        REFERENCES dim_veiculo ( sk_veiculo );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
